# Generated by Django 4.1.7 on 2023-03-17 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('exp', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('gpa', models.FloatField()),
                ('education', models.CharField(choices=[('hs', 'high scool'), ('c', 'college'), ('b', 'bachelor'), ('s', 'specialist'), ('m', 'master')], default='high scool', max_length=2)),
                ('achievenments', models.TextField(blank=True, max_length=5000, null=True)),
                ('hobbies', models.TextField(blank=True, max_length=5000, null=True)),
                ('rang', models.CharField(choices=[('no', 'no rang'), ('j', 'junior'), ('m', 'middle'), ('s', 'senior'), ('tl', 'team lead')], default='no rang', max_length=2)),
                ('techologes', models.ManyToManyField(blank=True, null=True, related_name='aspirants', to='aspirant.technologies')),
            ],
            options={
                'ordering': ['gpa'],
            },
        ),
    ]
