# Generated by Django 4.1.7 on 2023-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0004_alter_aspirant_education_alter_aspirant_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
